training:
  lr: 0.001
  weight-decay: 0.0000001
  bs: 5
  scheduler: 'steplr'
  gamma: 0.1
  step-size: 15
  rebalancing_fake: 0.3
  rebalancing_real: 1
  frames-per-video: 30 # Equidistant frames
  
model:
  image-size: 224
  patch-size: 7
  num-classes: 5
  dim: 512
  depth: 4
  dim-head: 64
  heads: 6
  mlp-dim: 1024
  emb-dim: 32
  dropout: 0.3
  emb-dropout: 0.3